// packages/vue/src/data/Avatar.vue
<script setup lang="ts">
/**
 * Avatar 头像
 *
 * @example Vue
 * <Avatar src="https://example.com/avatar.jpg" size="lg" />
 */
import { ref, computed } from 'vue';
import { type AvatarProps, type ColorType, type Size, cx } from '../types/aui-types';

const props = withDefaults(defineProps<AvatarProps>(), {
  size: 'md',
  shape: 'circle',
});

const imgError = ref(false);
const showText = computed(() => !props.src || imgError.value);

const sizeMap: Record<Size, string> = {
  xs: 'w-6 h-6 text-xs', sm: 'w-8 h-8 text-sm',
  md: 'w-10 h-10 text-base', lg: 'w-12 h-12 text-lg', xl: 'w-14 h-14 text-xl',
};

const colorMap: Record<ColorType, string> = {
  primary: 'bg-[#1677ff]', success: 'bg-[#52c41a]',
  warning: 'bg-[#faad14]', danger: 'bg-[#ff4d4f]',
  info: 'bg-[#1677ff]', gray: 'bg-[#8c8c8c]',
};

const sizeClass = computed(() => typeof props.size === 'number' ? '' : sizeMap[props.size as Size] ?? sizeMap.md);
const sizeStyle = computed(() => typeof props.size === 'number' ? { width: props.size, height: props.size } : {});
const bgClass = computed(() => {
  if (typeof props.color === 'string' && !Object.keys(colorMap).includes(props.color)) return '';
  return colorMap[props.color as ColorType] ?? colorMap.primary;
});
</script>

<template>
  <div
    :class="cx(
      'flex items-center justify-center overflow-hidden font-medium text-white shrink-0 select-none',
      sizeClass,
      shape === 'circle' ? 'rounded-full' : 'rounded-lg',
      bgClass,
      props.className ?? ''
    )"
    :style="sizeStyle"
  >
    <img v-if="src && !imgError" :src="src" alt="" class="w-full h-full object-cover" @error="imgError = true" />
    <span v-else>{{ text?.[0]?.toUpperCase() ?? '?' }}</span>
  </div>
</template>

// packages/react/src/data/Avatar.tsx
/**
 * Avatar 头像
 *
 * @example React
 * import { Avatar } from '@aui/react';
 * <Avatar src="https://example.com/avatar.jpg" size="lg" />
 * <Avatar text="李" size={64} color="primary" />
 *
 * @example Vue
 * <Avatar src="https://example.com/avatar.jpg" size="lg" />
 * <Avatar text="李" :size="64" color="primary" />
 */

import React, { useState } from 'react';
import { type AvatarProps, type ColorType, type Size, cx } from '@aui/core';

const sizeMap: Record<Size, string> = {
  xs:  'w-6 h-6 text-xs',
  sm:  'w-8 h-8 text-sm',
  md:  'w-10 h-10 text-base',
  lg:  'w-12 h-12 text-lg',
  xl:  'w-14 h-14 text-xl',
};

const colorMap: Record<ColorType, string> = {
  primary: 'bg-[#1677ff]',
  success: 'bg-[#52c41a]',
  warning: 'bg-[#faad14]',
  danger:  'bg-[#ff4d4f]',
  info:    'bg-[#1677ff]',
  gray:    'bg-[#8c8c8c]',
};

export const Avatar = React.forwardRef<HTMLDivElement, AvatarProps>(
  ({ src, size = 'md', shape = 'circle', text, color = 'primary', className, ...rest }, ref) => {
    const [imgError, setImgError] = useState(false);
    const showText = !src || imgError;

    const sizeClass = typeof size === 'number' ? '' : sizeMap[size as Size];
    const sizeStyle = typeof size === 'number' ? { width: size, height: size } : {};
    const shapeClass = shape === 'circle' ? 'rounded-full' : 'rounded-lg';

    const bgClass = typeof color === 'string' && !Object.keys(colorMap).includes(color)
      ? '' : colorMap[color as ColorType] || colorMap.primary;

    return (
      <div
        ref={ref}
        className={cx(
          'flex items-center justify-center overflow-hidden font-medium text-white shrink-0 select-none',
          sizeClass, shapeClass, !showText || text ? bgClass : '', className
        )}
        style={sizeStyle}
        {...rest}
      >
        {showText ? (
          <span>{text?.[0]?.toUpperCase() ?? '?'}</span>
        ) : (
          <img
            src={src}
            alt=""
            className="w-full h-full object-cover"
            onError={() => setImgError(true)}
          />
        )}
      </div>
    );
  }
);

Avatar.displayName = 'Avatar';
