// packages/vue/src/data/Statistic.vue
<script setup lang="ts">
/**
 * Statistic 统计数值
 *
 * @example Vue
 * <Statistic title="用户总数" :value="1024" prefix="↑" suffix="人" />
 */
import { computed } from 'vue';
import { type StatisticProps } from '../types/aui-types';

const props = withDefaults(defineProps<StatisticProps>(), {
  value: 0,
});

const displayValue = computed(() => {
  if (props.formatter) return props.formatter(Number(props.value));
  if (typeof props.value === 'number' && props.precision !== undefined) {
    return (props.value as number).toFixed(props.precision);
  }
  return String(props.value ?? '');
});
</script>

<template>
  <div class="flex flex-col">
    <span v-if="title" class="text-[14px] text-[#8c8c8c] mb-1">{{ title }}</span>
    <div class="flex items-baseline gap-1">
      <span v-if="prefix" class="text-[24px] text-[#262626]">{{ prefix }}</span>
      <span class="text-[24px] font-bold text-[#262626]" :style="valueStyle">{{ displayValue }}</span>
      <span v-if="suffix" class="text-[14px] text-[#8c8c8c]">{{ suffix }}</span>
    </div>
  </div>
</template>

// packages/react/src/data/Statistic.tsx
/**
 * Statistic 统计数值
 *
 * @example React
 * import { Statistic } from '@aui/react';
 * <Statistic title="用户总数" value={1024} prefix="↑" suffix="人" />
 *
 * @example Vue
 * <Statistic title="用户总数" :value="1024" prefix="↑" suffix="人" />
 */

import React, { useMemo } from 'react';
import { type StatisticProps, cx } from '@aui/core';

export const Statistic = React.forwardRef<HTMLDivElement, StatisticProps>(
  ({ title, value, prefix, suffix, valueStyle, precision, formatter, className, ...rest }, ref) => {
    const displayValue = useMemo(() => {
      if (formatter) return formatter(typeof value === 'number' ? value : parseFloat(String(value)));
      if (typeof value === 'number' && precision !== undefined) {
        return value.toFixed(precision);
      }
      return String(value ?? '');
    }, [value, precision, formatter]);

    return (
      <div ref={ref} className={cx('flex flex-col', className)} {...rest}>
        {title && <span className="text-[14px] text-[#8c8c8c] mb-1">{title}</span>}
        <div className="flex items-baseline gap-1">
          {prefix && <span className="text-[24px] text-[#262626]">{prefix}</span>}
          <span className="text-[24px] font-bold text-[#262626]" style={valueStyle}>
            {displayValue}
          </span>
          {suffix && <span className="text-[14px] text-[#8c8c8c]">{suffix}</span>}
        </div>
      </div>
    );
  }
);

Statistic.displayName = 'Statistic';
