// packages/vue/src/mobile/IndexBar.vue
<script setup lang="ts">
/** IndexBar 索引列表 */
import { type IndexBarProps } from '../types/aui-types';
const props = withDefaults(defineProps<IndexBarProps>(), { showAnchor: true });
const emit = defineEmits<{ select: [item: any] }>();
</script>

<template>
  <div class="flex">
    <!-- 索引内容 -->
    <div class="flex-1">
      <div v-for="group in data" :key="group.index" class="mb-4">
        <div class="px-4 py-1 bg-[#f5f5f5] text-[14px] font-medium text-[#8c8c8c] sticky top-0">{{ group.index }}</div>
        <div
          v-for="item in group.items" :key="item.key"
          class="px-4 py-3 border-b border-[#f0f0f0] flex items-center gap-3 cursor-pointer"
          @click="emit('select', item)"
        >
          <img v-if="item.avatar" :src="item.avatar" class="w-10 h-10 rounded-full object-cover" />
          <div class="flex-1">
            <div class="text-[14px] font-medium text-[#262626]">{{ item.title }}</div>
            <div v-if="item.description" class="text-[12px] text-[#8c8c8c] mt-0.5">{{ item.description }}</div>
          </div>
        </div>
      </div>
    </div>
    <!-- 侧边索引 -->
    <div v-if="showAnchor" class="w-5 flex flex-col items-center justify-center gap-0.5 py-2 sticky top-0 h-fit">
      <button
        v-for="(group, i) in data" :key="group.index"
        class="text-[10px] text-[#595959] hover:text-[#1677ff] transition-colors"
        @click="emit('select', group.items[0])"
      >
        {{ group.index }}
      </button>
    </div>
  </div>
</template>

// packages/react/src/mobile/IndexBar.tsx
/**
 * IndexBar 索引列表（移动端）
 *
 * @example React
 * import { IndexBar } from '@aui/react';
 * const data = [{ index: 'A', items: [{ key: '1', title: '张三' }] }];
 * <IndexBar data={data} onSelect={(item) => console.log(item)} />
 */

import React, { useState } from 'react';
import { type IndexBarProps, type IndexBarItem, cx } from '@aui/core';

export const IndexBar = React.forwardRef<HTMLDivElement, IndexBarProps>(
  ({ data = [], onSelect, showAnchor = true, indexes, className, ...rest }, ref) => {
    const [activeIndex, setActiveIndex] = useState('');
    const allIndexes = indexes ?? data.map((d) => d.index);

    const handleSelect = (item: IndexBarItem['items'][0]) => {
      onSelect?.(item as any);
      setActiveIndex(item.title);
    };

    return (
      <div ref={ref} className={cx('flex h-full', className)} {...rest}>
        {/* 主内容 */}
        <div className="flex-1 overflow-auto px-4">
          {data.map((group) => (
            <div key={group.index} className="mb-4">
              <div className="sticky top-0 bg-white py-2 text-[12px] font-medium text-[#8c8c8c] z-10">
                {group.index}
              </div>
              <div className="space-y-1">
                {group.items.map((item) => (
                  <div
                    key={item.key}
                    onClick={() => handleSelect(item)}
                    className="flex items-center gap-3 px-3 py-3 rounded-lg hover:bg-[#f5f5f5] transition-colors cursor-pointer"
                  >
                    {item.avatar && (
                      <img src={item.avatar} alt="" className="w-10 h-10 rounded-full object-cover" />
                    )}
                    <div>
                      <div className="text-[14px] text-[#262626]">{item.title}</div>
                      {item.description && (
                        <div className="text-[12px] text-[#8c8c8c]">{item.description}</div>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>

        {/* 侧边索引 */}
        {showAnchor && (
          <div className="flex flex-col items-center justify-center gap-1 px-1 py-4">
            {allIndexes.map((idx) => (
              <button
                key={idx}
                className={cx(
                  'w-4 h-4 text-[10px] font-medium rounded flex items-center justify-center transition-colors',
                  activeIndex === idx ? 'bg-[#1677ff] text-white' : 'text-[#8c8c8c] hover:text-[#1677ff]'
                )}
                onClick={() => {
                  const el = document.getElementById(`index-${idx}`);
                  el?.scrollIntoView({ behavior: 'smooth' });
                  setActiveIndex(idx);
                }}
              >
                {idx}
              </button>
            ))}
          </div>
        )}
      </div>
    );
  }
);

IndexBar.displayName = 'IndexBar';
