// packages/react/src/feedback/Popconfirm.tsx
/**
 * Popconfirm 气泡确认框
 *
 * @example React
 * import { Popconfirm, Button } from '@aui/react';
 * <Popconfirm title="确定删除？" onConfirm={handleDelete}>
 *   <Button danger>删除</Button>
 * </Popconfirm>
 */

import React, { useState, useRef, useEffect } from 'react';
import { type PopconfirmProps, type Placement, cx } from '@aui/core';

const placementMap: Record<Placement, string> = {
  top:         'bottom-full left-1/2 -translate-x-1/2 mb-2',
  bottom:      'top-full left-1/2 -translate-x-1/2 mt-2',
  left:        'right-full top-1/2 -translate-y-1/2 mr-2',
  right:       'left-full top-1/2 -translate-y-1/2 ml-2',
  topLeft:     'bottom-full left-0 mb-2',
  topRight:    'bottom-full right-0 mb-2',
  bottomLeft:  'top-full left-0 mt-2',
  bottomRight: 'top-full right-0 mt-2',
};

export const Popconfirm = React.forwardRef<HTMLDivElement, PopconfirmProps>(
  ({ title, description, onConfirm, onCancel, okText = '确定', cancelText = '取消', okType = 'primary', trigger = 'hover', placement = 'top', className, children, ...rest }, ref) => {
    const [visible, setVisible] = useState(false);
    const containerRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
      if (!visible) return;
      const handleClickOutside = (e: MouseEvent) => {
        if (containerRef.current && !containerRef.current.contains(e.target as Node)) {
          setVisible(false);
        }
      };
      document.addEventListener('mousedown', handleClickOutside);
      return () => document.removeEventListener('mousedown', handleClickOutside);
    }, [visible]);

    const handleConfirm = () => {
      onConfirm?.();
      setVisible(false);
    };

    const handleCancel = () => {
      onCancel?.();
      setVisible(false);
    };

    return (
      <div ref={ref} className={cx('relative inline-flex', className)} {...rest}>
        <div
          onClick={trigger === 'click' ? () => setVisible(!visible) : undefined}
          onMouseEnter={trigger === 'hover' ? () => setVisible(true) : undefined}
          onMouseLeave={trigger === 'hover' ? () => setVisible(false) : undefined}
        >
          {children}
        </div>

        {visible && (
          <div className={cx('absolute z-[1400] w-52 bg-white rounded-lg shadow-lg border border-[#f0f0f0] p-3', placementMap[placement])}>
            {title && <div className="text-[14px] font-medium text-[#262626] mb-1">{title}</div>}
            {description && <div className="text-[12px] text-[#8c8c8c] mb-3">{description}</div>}
            <div className="flex justify-end gap-2">
              <button
                onClick={handleCancel}
                className="px-3 py-1 text-xs rounded border border-[#d9d9d9] text-[#595959] hover:border-[#4096ff] hover:text-[#4096ff] transition-colors"
              >
                {cancelText}
              </button>
              <button
                onClick={handleConfirm}
                className={cx(
                  'px-3 py-1 text-xs rounded text-white transition-colors',
                  okType === 'primary' ? 'bg-[#1677ff] hover:bg-[#4096ff]' : 'bg-[#ff4d4f] hover:bg-[#ff7875]'
                )}
              >
                {okText}
              </button>
            </div>
          </div>
        )}
      </div>
    );
  }
);

Popconfirm.displayName = 'Popconfirm';

// packages/vue/src/feedback/Popconfirm.vue
<script setup lang="ts">
/** Popconfirm 气泡确认框 */
import { ref } from 'vue';
import { type PopconfirmProps } from '../types/aui-types';
const props = withDefaults(defineProps<PopconfirmProps>(), {
  title: '确定执行此操作？',
  trigger: 'click',
  placement: 'top',
});
const emit = defineEmits<{ confirm: []; cancel: [] }>();
const visible = ref(false);
const toggle = () => { visible.value = !visible.value; };
const handleConfirm = () => { visible.value = false; emit('confirm'); };
const handleCancel = () => { visible.value = false; emit('cancel'); };
</script>

<template>
  <span class="relative inline-flex">
    <span @click="trigger === 'click' ? toggle() : undefined" @mouseenter="trigger === 'hover' ? visible = true : undefined" @mouseleave="trigger === 'hover' ? visible = false : undefined">
      <slot />
    </span>
    <Teleport to="body">
      <div v-if="visible" class="fixed inset-0 z-[1300]" @click="visible = false">
        <div class="absolute bg-white rounded-lg shadow-xl border border-[#f0f0f0] p-4 min-w-[200px] z-[1301]" :class="placement === 'top' ? 'bottom-full left-1/2 -translate-x-1/2 mb-2' : ''">
          <p class="text-[14px] text-[#262626] mb-3">{{ title }}</p>
          <div class="flex gap-2 justify-end">
            <button class="px-3 py-1 text-[14px] text-[#595959] hover:text-[#262626]" @click="handleCancel">取消</button>
            <button class="px-3 py-1 text-[14px] bg-[#1677ff] text-white rounded hover:bg-[#0958d9]" @click="handleConfirm">确定</button>
          </div>
        </div>
      </div>
    </Teleport>
  </span>
</template>
